---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: us-mlpredictor-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: us-mlpredictor
  template:
    metadata:
      labels:
        app: us-mlpredictor
    spec:
      containers:
      - name: us-mlpredictor
        image: docker.io/kurisuandhutao/cs401_proj2:0.0.4
        ports:
        - containerPort: 5018